name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build release
        run: cargo build --verbose --release
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/ai_address_backend
      - name: Clean older release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
